languageCode = "en"
languageName = "English"
weight = 1

title = "Incinta Fertility Center Blog"
description = "Expert insights and guidance on fertility, reproductive health, and your journey to parenthood"
copyright = "Copyright © 2024 Incinta Fertility Center. All rights reserved."

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  logo = "/img/logo.png"
  dateFormat = "2 January 2006"

[author]
  name = "Incinta Fertility Center"
  image = "/img/logo.png"
  headline = "Leading fertility clinic providing comprehensive reproductive health services"
  bio = "Incinta Fertility Center is dedicated to helping individuals and couples achieve their dreams of parenthood through personalized, compassionate care and cutting-edge reproductive technologies."
  links = [
    { linkedin = "https://linkedin.com/company/incinta-fertility" },
    { facebook = "https://facebook.com/incintafertility" },
    { email = "mailto:info@incintafertility.com" }
  ]