baseURL = 'https://incintafertility.com/'
languageCode = 'en-us'
title = 'Incinta Fertility Center'
theme = 'blowfish'

[params]
  description = "Leading fertility clinic providing comprehensive reproductive health services"
  subtitle = "Your Journey to Parenthood Starts Here"
  featured_image = "/images/hero-bg.jpg"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "Our Team"
    url = "/team/"
    weight = 3
  [[menu.main]]
    name = "Success Stories"
    url = "/success-stories/"
    weight = 4
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 6
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 7
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8
